import * as THREE from './vendor/three.module.js';
import * as CANNON from './vendor/cannon-es.js';
const $=id=>document.getElementById(id),zh=false;
const copy=zh?{level:'Level',hint:'按住向下拖动，削下一整片',sub:'削片翘起 · 碎块落下 · 找到 Ray',win:'找到 Ray了！',reward:'完成雕刻 · +25 金币',next:'下一块肥皂',again:'再切一次',phrases:['太放松了！','太神奇了！','太流畅了！','快找到宝藏了！'],lost:'时间到了',retry:'再试一次'}:{level:'Level',hint:'Hold & drag down to peel',sub:'PEEL · CRUMBLE · REVEAL RAY',win:'Ray revealed!',reward:'Carving complete · +25 coins',next:'Next soap',again:'Try again',phrases:['So relaxing!','Amazing!','So smooth!','Almost there!'],lost:'Time is up',retry:'Try again'};
$('instruction').textContent=copy.hint;$('subinstruction').textContent=copy.sub;$('next').textContent=copy.next;$('again').textContent=copy.again;
const root=$('game'),scene=new THREE.Scene();
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0xf6b9d4);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.NoToneMapping;renderer.outputColorSpace=THREE.SRGBColorSpace;root.prepend(renderer.domElement);
const camera=new THREE.OrthographicCamera(-3,3,4.65,-4.65,.1,70);camera.position.set(0,10.8,7.8);camera.lookAt(0,.15,-.9);
scene.add(new THREE.HemisphereLight(0xf5fbff,0xe2b3c7,.85));const light=new THREE.DirectionalLight(0xffffff,1.65);light.position.set(5,10,-3);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-8,right:8,top:9,bottom:-8});light.shadow.normalBias=.022;light.shadow.bias=-.0002;light.shadow.radius=3;scene.add(light);
const fillLight=new THREE.DirectionalLight(0xffe5f0,.28);fillLight.position.set(-4,5,6);scene.add(fillLight);
const fg=new THREE.PlaneGeometry(120,120,1,180),fc=[];for(let i=0;i<fg.attributes.position.count;i++){const z=-fg.attributes.position.getY(i),c=new THREE.Color(0xefb0ce).lerp(new THREE.Color(0xffdeed),THREE.MathUtils.clamp((z+9)/18,0,1));c.multiplyScalar(.92);fc.push(c.r,c.g,c.b);}fg.setAttribute('color',new THREE.Float32BufferAttribute(fc,3));const floor=new THREE.Mesh(fg,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;floor.receiveShadow=true;scene.add(floor);
// Procedural studio reflections for polished sides and the metal blade.
const envScene=new THREE.Scene();envScene.background=new THREE.Color(0xf3d3e1);for(const [x,y,z,sx,sy,sz,color]of [[-4,2,0,.1,5,5,0xfff5e7],[3,3,-2,.1,4,2,0xba7996],[0,5,0,4,.1,5,0xffedf5],[0,0,-4,5,5,.1,0xd6a2b9]]){const m=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),new THREE.MeshBasicMaterial({color}));m.position.set(x,y,z);envScene.add(m);}const envTarget=new THREE.WebGLCubeRenderTarget(128,{type:THREE.HalfFloatType});new THREE.CubeCamera(.1,30,envTarget).update(renderer,envScene);const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromCubemap(envTarget.texture).texture;envTarget.dispose();pmrem.dispose();
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const shadowContext=shadowCanvas.getContext('2d'),gradient=shadowContext.createRadialGradient(64,64,10,64,64,64);gradient.addColorStop(0,'rgba(70,58,45,.38)');gradient.addColorStop(.65,'rgba(70,58,45,.26)');gradient.addColorStop(1,'rgba(70,58,45,0)');shadowContext.fillStyle=gradient;shadowContext.fillRect(0,0,128,128);const softShadow=new THREE.Mesh(new THREE.PlaneGeometry(2.8,4.6),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));softShadow.rotation.x=-Math.PI/2;softShadow.rotation.z=-.22;softShadow.position.set(-.6,.006,.6);scene.add(softShadow);
const soapRoot=new THREE.Group();soapRoot.rotation.x=-Math.PI/2;soapRoot.scale.z=.8;soapRoot.position.set(0,.404,2.25);scene.add(soapRoot);
// Soap has a smooth surface with fine embedded specks, not scored grid lines.
const soapCanvas=document.createElement('canvas');soapCanvas.width=512;soapCanvas.height=768;const soapCtx=soapCanvas.getContext('2d');soapCtx.fillStyle='#f4bfd4';soapCtx.fillRect(0,0,512,768);for(let i=0;i<22000;i++){const x=Math.random()*512,y=Math.random()*768,r=.3+Math.random()*1.5;soapCtx.fillStyle=Math.random()<.035?'rgba(160,65,110,.18)':Math.random()<.55?'rgba(255,255,255,.22)':'rgba(205,105,150,.10)';soapCtx.beginPath();soapCtx.arc(x,y,r,0,Math.PI*2);soapCtx.fill();}
soapCtx.save();soapCtx.translate(256,384);soapCtx.rotate(-Math.PI/2);soapCtx.font='bold 92px Arial';soapCtx.textAlign='center';soapCtx.textBaseline='middle';soapCtx.lineWidth=3;soapCtx.strokeStyle='rgba(145,52,93,.35)';soapCtx.strokeText('SOAP',2,3);soapCtx.strokeStyle='rgba(245,255,255,.65)';soapCtx.strokeText('SOAP',-2,-2);soapCtx.restore();const speckMap=new THREE.CanvasTexture(soapCanvas);speckMap.colorSpace=THREE.SRGBColorSpace;
const stampCanvas=document.createElement('canvas');stampCanvas.width=512;stampCanvas.height=768;const stampCtx=stampCanvas.getContext('2d');stampCtx.fillStyle='#808080';stampCtx.fillRect(0,0,512,768);stampCtx.save();stampCtx.translate(256,384);stampCtx.rotate(-Math.PI/2);stampCtx.font='bold 92px Arial';stampCtx.textAlign='center';stampCtx.textBaseline='middle';stampCtx.lineWidth=5;stampCtx.strokeStyle='#bcbcbc';stampCtx.strokeText('SOAP',0,0);stampCtx.fillStyle='#696969';stampCtx.fillText('SOAP',0,0);stampCtx.restore();const stampMap=new THREE.CanvasTexture(stampCanvas);
const faceMat=new THREE.MeshPhysicalMaterial({color:0xcc568f,roughness:.18,metalness:0,clearcoat:1,clearcoatRoughness:.12,envMapIntensity:1.1,side:THREE.DoubleSide});const sideMat=new THREE.MeshPhysicalMaterial({color:0xcc568f,emissive:0x9e3b69,emissiveIntensity:.12,roughness:.3,metalness:0,clearcoat:.65,clearcoatRoughness:.2,envMapIntensity:.35,side:THREE.DoubleSide});const chipMat=new THREE.MeshPhysicalMaterial({color:0xcc568f,roughness:.2,metalness:0,clearcoat:1,clearcoatRoughness:.14,envMapIntensity:1});const rabbitMat=new THREE.MeshPhysicalMaterial({color:0x74848a,roughness:.4,metalness:0,clearcoat:.12,envMapIntensity:.25});
const rabbit=new THREE.Group();soapRoot.add(rabbit);
const logoMaterial=new THREE.MeshPhysicalMaterial({color:0xff1736,roughness:.28,metalness:0,clearcoat:.45});
function logoPart(shape,x,y){const mesh=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.10,bevelEnabled:true,bevelSize:.015,bevelThickness:.015,bevelSegments:3,curveSegments:20}),logoMaterial);mesh.position.set(x,y,x*.16+y*.08);mesh.castShadow=mesh.receiveShadow=true;rabbit.add(mesh);}
function logoBar(x,y,w,h){const s=new THREE.Shape(),r=.035;s.moveTo(r,0);s.lineTo(w-r,0);s.quadraticCurveTo(w,0,w,r);s.lineTo(w,h-r);s.quadraticCurveTo(w,h,w-r,h);s.lineTo(r,h);s.quadraticCurveTo(0,h,0,h-r);s.lineTo(0,r);s.quadraticCurveTo(0,0,r,0);logoPart(s,x,y);}
function logoRing(x,y){const s=new THREE.Shape();s.absellipse(.14,.20,.14,.20,0,Math.PI*2,false);const h=new THREE.Path();h.absellipse(.14,.20,.064,.12,0,Math.PI*2,true);s.holes.push(h);logoPart(s,x,y);}
// Rounded extruded Ray lettering, centered inside the soap.
function logoStroke(x1,y1,x2,y2,w){const dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),nx=-dy/len*w/2,ny=dx/len*w/2,s=new THREE.Shape();s.moveTo(x1+nx,y1+ny);s.lineTo(x2+nx,y2+ny);s.lineTo(x2-nx,y2-ny);s.lineTo(x1-nx,y1-ny);s.closePath();logoPart(s,0,0);}
logoBar(-.67,-.28,.10,.68);
const rBowl=new THREE.Shape();rBowl.moveTo(-.59,.40);rBowl.lineTo(-.40,.40);rBowl.bezierCurveTo(-.12,.40,-.12,.02,-.40,.02);rBowl.lineTo(-.59,.02);rBowl.closePath();const rHole=new THREE.Path();rHole.moveTo(-.56,.31);rHole.lineTo(-.56,.11);rHole.lineTo(-.40,.11);rHole.bezierCurveTo(-.25,.11,-.25,.31,-.40,.31);rHole.closePath();rBowl.holes.push(rHole);logoPart(rBowl,0,0);logoStroke(-.43,.06,-.19,-.28,.10);
logoRing(-.08,-.28);logoBar(.15,-.28,.08,.40);
logoStroke(.31,.12,.48,-.17,.09);logoStroke(.67,.12,.39,-.45,.09);

rabbit.position.set(0,2.25,-.18);
const knife=new THREE.Group();soapRoot.add(knife);const bladeShape=new THREE.Shape();bladeShape.moveTo(-2.45,.09);bladeShape.quadraticCurveTo(-2.08,-.06,-1.56,-.095);bladeShape.lineTo(-.4,-.095);for(let x=-.4;x<1.66;x+=.075){bladeShape.lineTo(x+.032,-.125);bladeShape.lineTo(x+.075,-.095);}bladeShape.lineTo(1.74,-.095);bladeShape.lineTo(1.74,.14);bladeShape.lineTo(-1.45,.16);bladeShape.quadraticCurveTo(-2.03,.14,-2.45,.09);
const bladeGeo=new THREE.ExtrudeGeometry(bladeShape,{depth:.045,bevelEnabled:true,bevelSize:.009,bevelThickness:.008,bevelSegments:2});const steel=new THREE.MeshStandardMaterial({color:0xbdb0a8,roughness:.33,metalness:.75,envMapIntensity:.7});const blade=new THREE.Mesh(bladeGeo,steel);blade.castShadow=true;knife.add(blade);knife.rotation.z=-.13;knife.scale.setScalar(.78);
const handle=new THREE.Mesh(new THREE.BoxGeometry(1.03,.36,.35),new THREE.MeshStandardMaterial({color:0x25221f,roughness:.44,metalness:.1}));handle.position.set(2.15,.035,.06);handle.castShadow=true;knife.add(handle);const bolster=new THREE.Mesh(new THREE.BoxGeometry(.15,.37,.36),steel);bolster.position.set(1.69,.035,.06);knife.add(bolster);
const RX=1.22,RY=1.82,CY=2.25,FRONT=.72,BACK=-.48,DEPTH=.12,LAYERS=10,CELL=.18,ROWS=100;
let returning=false,returnArmed=false,barDirty=false,lastDragDirection=0;
let level=1,coins=25,layer=0,cutY=CY+RY+.25,targetY=cutY,started=false,paused=false,completed=false,down=false,auto=false,lastY=0,movement=0,elapsed=0,cooldown=0,winDelay=0,fallTime=0,msgTime=0,pieces=[],peeling=[],cutCount=0;
let shellFront,shellSide;
const frameHeights=()=>FRONT-layer*DEPTH;
const width=y=>RX*Math.sqrt(Math.max(0,1-((y-CY)/RY)**2));
// Low-restitution rigid bodies: chips hit the bar, ground and one another.
const physics=new CANNON.World({gravity:new CANNON.Vec3(0,-9.81,0),allowSleep:true});physics.broadphase=new CANNON.SAPBroadphase(physics);physics.broadphase.axisIndex=0;physics.solver.iterations=4;physics.solver.tolerance=.001;
const stoneContact=new CANNON.Material('soap-chip');physics.defaultContactMaterial.friction=.58;physics.defaultContactMaterial.restitution=.09;physics.addContactMaterial(new CANNON.ContactMaterial(stoneContact,stoneContact,{friction:.58,restitution:.09,contactEquationStiffness:1e7,contactEquationRelaxation:4}));
const groundBody=new CANNON.Body({mass:0,material:stoneContact,shape:new CANNON.Plane(),collisionFilterGroup:1,collisionFilterMask:4});groundBody.quaternion.setFromEuler(-Math.PI/2,0,0);physics.addBody(groundBody);
const collisionRows=[];
for(let i=0;i<14;i++){const localY=CY-RY+(i+.5)*RY*2/14,w=width(localY)*.96,shape=new CANNON.Box(new CANNON.Vec3(Math.max(.08,w),.27,RY/14));const body=new CANNON.Body({mass:0,material:stoneContact,shape,collisionFilterGroup:2,collisionFilterMask:4});body.position.set(0,.29,CY-localY);physics.addBody(body);collisionRows.push({body,shape,localY,height:.54});}
const cutterBody=new CANNON.Body({type:CANNON.Body.KINEMATIC,mass:0,material:stoneContact,shape:new CANNON.Box(new CANNON.Vec3(1.45,.38,.085)),collisionFilterGroup:2,collisionFilterMask:4});physics.addBody(cutterBody);let cutterZ=0;
function updateCutter(dt){const z=CY-targetY+.06,previousZ=cutterZ,delta=z-previousZ;
 const bladeY=.404+frameHeights()*.8+.34;
 cutterBody.position.set(.15,bladeY,z);cutterBody.velocity.set(0,0,THREE.MathUtils.clamp(delta/Math.max(.01,dt),-4,4));cutterZ=z;cutterBody.aabbNeedsUpdate=true;cutterBody.collisionResponse=!completed;
 // Sweep the blade between input samples, including sleeping chips on return.
 // This prevents a fast reverse drag from teleporting through the fragments.
 if(!completed&&delta<-.0001){const half=CELL*.42,speed=Math.min(3.5,Math.max(.6,-delta/Math.max(.01,dt)));
  for(const p of pieces){const body=p.body;if(!body)continue;const pos=body.position;
   if(Math.abs(pos.x-.15)>1.45+half||Math.abs(pos.y-bladeY)>.38+half||pos.z<z-.085-half||pos.z>previousZ+.085+half)continue;
   body.wakeUp();body.position.z=Math.min(pos.z,z-.085-half);body.velocity.z=Math.min(body.velocity.z,-speed);body.velocity.x+=(pos.x>=0?1:-1)*.12;body.velocity.y=Math.max(body.velocity.y,.06);body.angularVelocity.x=Math.max(body.angularVelocity.x,.6);body.aabbNeedsUpdate=true;
  }
 }
}
const chunkShape=new CANNON.Box(new CANNON.Vec3(CELL*.84/2,CELL*.84/2,CELL*.80/2));
function updateCollisionBar(){for(const row of collisionRows){const front=frameHeights()-(row.localY>=cutY?DEPTH:0),height=Math.max(.015,(front-BACK)*.8*Math.sqrt(Math.max(0,1-((row.localY-CY)/RY)**2)));if(Math.abs(height-row.height)<.00001)continue;row.height=height;row.shape.halfExtents.y=height/2;row.shape.updateConvexPolyhedronRepresentation();row.shape.updateBoundingSphereRadius();row.body.position.y=.02+height/2;row.body.updateBoundingRadius();row.body.aabbNeedsUpdate=true;}physics.broadphase.dirty=true;}
function createRigidChip(p,seed=false){const body=new CANNON.Body({mass:.025,material:stoneContact,shape:chunkShape,position:new CANNON.Vec3(p.pos.x,p.pos.y,p.pos.z),linearDamping:.10,angularDamping:.25,allowSleep:true,sleepSpeedLimit:.15,sleepTimeLimit:.65,collisionFilterGroup:4,collisionFilterMask:7});body.quaternion.setFromEuler(p.rx||0,p.ry||0,p.rz||0);if(!seed){body.velocity.set(p.x/RX*.22+(Math.random()-.5)*.22,.12+Math.random()*.24,.25+Math.random()*.35);body.angularVelocity.set((Math.random()-.5)*3,(Math.random()-.5)*2.4,(Math.random()-.5)*3);}physics.addBody(body);p.body=body;p.rigidAge=0;p.seed=seed;p.status='rigid';return body;}
function syncRigidChips(){let dirty=false;for(const p of pieces){if(!p.body)continue;if(p.body.sleepState===CANNON.Body.SLEEPING&&p.syncedSleeping)continue;p.syncedSleeping=p.body.sleepState===CANNON.Body.SLEEPING;p.pos.set(p.body.position.x,p.body.position.y,p.body.position.z);dummy.position.copy(p.pos);dummy.quaternion.set(p.body.quaternion.x,p.body.quaternion.y,p.body.quaternion.z,p.body.quaternion.w);dummy.scale.setScalar(p.fadeScale??1);dummy.updateMatrix();cubes.setMatrixAt(p.id,dummy.matrix);dirty=true;}if(dirty)cubes.instanceMatrix.needsUpdate=true;}
function newMesh(material){const mesh=new THREE.Mesh(new THREE.BufferGeometry(),material);mesh.castShadow=true;mesh.receiveShadow=true;soapRoot.add(mesh);return mesh;}
shellFront=newMesh(faceMat);shellSide=newMesh(sideMat);
const cutRim=new THREE.LineLoop(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xb9658c,transparent:true,opacity:.25}));soapRoot.add(cutRim);
function updateBar(){softShadow.visible=layer<LAYERS;softShadow.material.opacity=.45*Math.max(0,1-layer/LAYERS);rabbit.visible=true;updateCollisionBar();const fp=[],sp=[];const front=frameHeights(),mid=(FRONT+BACK)/2,half=(FRONT-BACK)/2;
 const radius=Math.sqrt(Math.max(0,1-((front-mid)/half)**2));const rimPoints=[];if(layer>0&&front>mid){for(let i=0;i<360;i++){const angle=i/180*Math.PI*2;rimPoints.push(new THREE.Vector3(RX*radius*Math.cos(angle),CY+RY*radius*Math.sin(angle),front+.003));}}cutRim.geometry.dispose();cutRim.geometry=new THREE.BufferGeometry().setFromPoints(rimPoints);cutRim.visible=rimPoints.length>0&&layer<LAYERS;
 const surface=(x,y,top)=>{const radial=Math.max(0,1-(x/RX)**2-((y-CY)/RY)**2);const upper=mid+half*Math.sqrt(radial),cutPlane=front-(y>=cutY?DEPTH:0);return [x,y,top?Math.min(upper,cutPlane):mid-half*Math.sqrt(radial)];};
 const quad=(out,a,b,c,d)=>out.push(...a,...b,...c,...a,...c,...d);
 for(let row=0;row<100;row++){const y0=CY-RY+row/100*RY*2,y1=CY-RY+(row+1)/100*RY*2,w0=width(y0),w1=width(y1);for(let col=0;col<48;col++){const u0=col/48*2-1,u1=(col+1)/48*2-1;const cx=(w0+w1)*(u0+u1)/4,cy=(y0+y1)/2,radial=Math.max(0,1-(cx/RX)**2-((cy-CY)/RY)**2);if(front-(cy>=cutY?DEPTH:0)<=mid-half*Math.sqrt(radial))continue;for(const top of [true,false]){const out=top?fp:sp;quad(out,surface(w0*u0,y0,top),surface(w0*u1,y0,top),surface(w1*u1,y1,top),surface(w1*u0,y1,top));}}}
 for(const [mesh,pos]of [[shellFront,fp],[shellSide,sp]]){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));const uv=[],normals=[],surfaceColors=[];for(let i=0;i<pos.length;i+=3){const x=pos[i],y=pos[i+1],z=pos[i+2];uv.push((x+RX)/(RX*2),(y-CY+RY)/(RY*2));const originalTop=mid+half*Math.sqrt(Math.max(0,1-(x/RX)**2-((y-CY)/RY)**2));const n=mesh===shellFront&&z<originalTop-.0001?new THREE.Vector3(0,0,1):new THREE.Vector3(x/(RX*RX),(y-CY)/(RY*RY),(z-mid)/Math.max(.001,half*half)).normalize();normals.push(n.x,n.y,n.z);const plane=front-(y>=cutY?DEPTH:0),blend=mesh===shellFront?THREE.MathUtils.smoothstep(originalTop-plane,0,.028):0;const surfaceColor=new THREE.Color(.92,.79,.85).lerp(new THREE.Color(1.12,1.02,1.06),blend);surfaceColors.push(surfaceColor.r,surfaceColor.g,surfaceColor.b);}g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));g.setAttribute('color',new THREE.Float32BufferAttribute(surfaceColors,3));faceMat.vertexColors=true;g.computeBoundingSphere();mesh.geometry.dispose();mesh.geometry=g;mesh.visible=layer<LAYERS;}}
// A scored layer stays connected as it peels. Pieces release only after
// the lifted ribbon curls over the blade, rather than spawning from nowhere.
const cubeGeo=new THREE.BoxGeometry(CELL*.84,CELL*.84,CELL*.80),maxPieces=6000;
const cubes=new THREE.InstancedMesh(cubeGeo,chipMat,maxPieces);cubes.instanceMatrix.setUsage(THREE.DynamicDrawUsage);cubes.castShadow=true;cubes.receiveShadow=true;cubes.frustumCulled=false;scene.add(cubes);const dummy=new THREE.Object3D(),hide=new THREE.Matrix4().makeScale(0,0,0);for(let i=0;i<maxPieces;i++)cubes.setMatrixAt(i,hide);cubes.instanceMatrix.needsUpdate=true;
function setPiece(p){dummy.position.copy(p.pos);dummy.rotation.set(p.rx||0,p.ry||0,p.rz||0);dummy.scale.set(p.sx||1,p.sy||1,1);dummy.updateMatrix();cubes.setMatrixAt(p.id,dummy.matrix);}
function rabbitAt(x,y,z){return Math.abs(x)<.97&&y>1.78&&y<2.68&&z<-.02;}
function prepareLayer(){peeling=[];const z=frameHeights()-.04;for(let y=CY-RY+CELL*.5;y<CY+RY;y+=CELL)for(let x=-RX+CELL*.5;x<RX;x+=CELL){if((x/RX)**2+((y-CY)/RY)**2>.96||rabbitAt(x,y,z))continue;const id=pieces.length;if(id>=maxPieces)continue;const p={id,x,y,z,status:'attached',pos:new THREE.Vector3(),rx:0,ry:0,rz:0,age:0,releaseOffset:Math.random()*.38};pieces.push(p);peeling.push(p);cubes.setMatrixAt(id,hide);}cubes.instanceMatrix.needsUpdate=true;}
function release(p){p.pos.y+=.10;p.rx+=(Math.random()-.5)*.5;p.ry+=(Math.random()-.5)*.6;p.rz+=(Math.random()-.5)*.4;createRigidChip(p);}
function movePeel(dt){const front=frameHeights();soapRoot.updateMatrixWorld();let dirty=false;
 for(const p of peeling){if(p.status==='attached'&&p.y>=cutY){p.status='peel';cutCount++;}if(p.status!=='peel')continue;
  const distance=p.y-cutY;
  // Preserve row pitch around a short hinge, then keep the lifted grid flat.
  // A tight semicircle made consecutive thick tiles overlap in projection.
  const hinge=.42,maxAngle=.48,radius=hinge/maxAngle,arc=Math.min(distance*1.15,hinge),theta=arc/radius,tail=Math.max(0,distance*1.15-hinge)*1.32;
  const yy=cutY+radius*Math.sin(theta)+tail*Math.cos(maxAngle),zz=front+.08+radius*(1-Math.cos(theta))+tail*Math.sin(maxAngle);
  p.pos.set(p.x,yy,zz);soapRoot.localToWorld(p.pos);p.rx=Math.atan2(.45*Math.sin(theta),Math.cos(theta))-Math.PI/2;p.ry=.10;p.rz=0;setPiece(p);dirty=true;
  p.age+=dt;if(p.age>.08+p.releaseOffset*.18||distance>.22||cooldown>0)release(p);
 }
 if(dirty)cubes.instanceMatrix.needsUpdate=true;
}
let clearBatches=[];
function moveDebris(dt){updateCutter(dt);for(const batch of clearBatches){batch.remaining-=dt;if(batch.remaining>0)continue;for(const p of batch.pieces){if(p.body)physics.removeBody(p.body);p.body=null;p.status='gone';cubes.setMatrixAt(p.id,hide);}cubes.instanceMatrix.needsUpdate=true;}clearBatches=clearBatches.filter(batch=>batch.remaining>0);physics.step(1/60,dt,3);syncRigidChips();}
function seedDebris(){cutterBody.collisionResponse=false;for(let side=0;side<2;side++)for(let iy=0;iy<(side===0?3:2);iy++)for(let iz=0;iz<5;iz++)for(let ix=0;ix<5;ix++){const x=(side===0?1.4:-1.4)+(side===0?1:-1)*ix*CELL*.97,z=-.85-iz*CELL*.97;const p={id:pieces.length,x,y:0,status:'rigid',pos:new THREE.Vector3(x+(Math.random()-.5)*.07,CELL*.50+iy*CELL*.97,z+(Math.random()-.5)*.07),rx:(Math.random()-.5)*.3,ry:Math.random()*1.2,rz:(Math.random()-.5)*.3};pieces.push(p);createRigidChip(p,true);}for(let i=0;i<45;i++)physics.step(1/60);for(const p of pieces)if(p.body){p.body.velocity.setZero();p.body.angularVelocity.setZero();p.body.sleep();}syncRigidChips();cutterZ=CY-targetY+.06;}
function updateKnife(){knife.position.set(.65,targetY+.11,frameHeights()-.018+(returning?.14:0));}
function say(t){$('message').textContent=t;$('message').style.opacity=1;msgTime=1.3;}
function advance(y){if(paused||completed)return;started=true;$('hint').style.opacity=0;const next=THREE.MathUtils.clamp(y,CY-RY-1.25,CY+RY+.25);const descending=next<targetY-.00001;targetY=next;
 if(returning){if(!descending)returnArmed=true;if(descending&&!returnArmed){updateKnife();return;}if(descending)returning=false;else{if(targetY>=CY+RY+.24)returning=false;updateKnife();return;}}
 if(descending&&targetY<cutY){cutY=targetY;barDirty=true;$('fill').style.width=`${(layer+Math.min(1,(CY+RY+.25-cutY)/(RY*2+.5)))/LAYERS*100}%`;}
 updateKnife();if(descending&&cutY<=CY-RY-.24){movePeel(0);finishLayer();}}
function finishLayer(){cooldown=0;for(const p of peeling)if(p.status==='peel')release(p);layer++;cutY=CY+RY+.25;returning=true;returnArmed=false;updateBar();updateKnife();if(layer>=LAYERS){completed=true;knife.visible=false;shellFront.visible=shellSide.visible=false;fallTime=0;clearAllFragments();beginReveal();winDelay=2.1;$('fill').style.width='100%';say(copy.win);confetti();}else prepareLayer();}
let revealTime=-1,revealStart=new THREE.Vector3(),revealTarget=new THREE.Vector3(),revealRotation=new THREE.Quaternion();
function beginReveal(){scene.attach(rabbit);revealStart.copy(rabbit.position);revealRotation.copy(rabbit.quaternion);const towardsCamera=new THREE.Vector3().subVectors(camera.position,revealStart).normalize();revealTarget.copy(revealStart).addScaledVector(towardsCamera,2.1);revealTime=0;}
function animateReveal(dt){if(revealTime<0)return;revealTime+=dt;const t=Math.min(1,revealTime/1.6),ease=1-Math.pow(1-t,3);rabbit.position.lerpVectors(revealStart,revealTarget,ease);rabbit.scale.setScalar(THREE.MathUtils.lerp(1,1.65,ease));rabbit.quaternion.slerpQuaternions(revealRotation,camera.quaternion,ease);rabbit.rotateY(Math.PI*2*(1-ease));if(t>=1)rabbit.rotateY(Math.sin((revealTime-1.6)*1.4)*.16);}
const confettiMaterial=new THREE.MeshBasicMaterial({side:THREE.DoubleSide}),confGeo=new THREE.PlaneGeometry(.055,.085),conf=new THREE.InstancedMesh(confGeo,confettiMaterial,360);scene.add(conf);let confettiPieces=[];for(let i=0;i<360;i++)conf.setMatrixAt(i,hide);
function confetti(){confettiPieces=[];for(let i=0;i<360;i++){const c=new THREE.Color([0xff387d,0xffcd4f,0x80ddff,0xffffff,0xbda2ff][i%5]);conf.setColorAt(i,c);confettiPieces.push({id:i,pos:new THREE.Vector3((Math.random()-.5)*2,2+Math.random()*2,1),vel:new THREE.Vector3((Math.random()-.5)*3,2+Math.random()*2,(Math.random()-.5)*2),age:0});}conf.instanceColor.needsUpdate=true;}
function clearAllFragments(){for(const p of pieces){if(p.body)physics.removeBody(p.body);p.body=null;p.status='gone';cubes.setMatrixAt(p.id,hide);}peeling=[];clearBatches=[];cubes.instanceMatrix.needsUpdate=true;}
function showResult(won){completed=true;stopInput();if(won){clearAllFragments();confetti();coins+=25;$('coins').textContent=coins;}$('resultTitle').textContent=won?copy.win:copy.lost;$('resultText').textContent=won?copy.reward:copy.retry;$('next').textContent=won?copy.next:copy.retry;$('result').classList.add('show');}
function timer(){const s=Math.max(0,120-Math.floor(elapsed));$('timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
function reset(next=false){stopInput();revealTime=-1;if(next)level++;returning=false;returnArmed=false;barDirty=false;lastDragDirection=0;layer=0;cutY=targetY=CY+RY+.25;started=paused=completed=down=auto=false;elapsed=cooldown=winDelay=msgTime=cutCount=0;for(const p of pieces)if(p.body)physics.removeBody(p.body);for(let i=0;i<pieces.length;i++)cubes.setMatrixAt(i,hide);pieces=[];peeling=[];clearBatches=[];confettiPieces=[];for(let i=0;i<360;i++)conf.setMatrixAt(i,hide);conf.instanceMatrix.needsUpdate=true;soapRoot.add(rabbit);rabbit.position.set(0,2.25,-.18);rabbit.rotation.set(0,0,0);rabbit.scale.setScalar(1);fallTime=0;const color=0xcc568f;faceMat.color.setHex(0xcc568f);sideMat.color.setHex(color);chipMat.color.setHex(0xcc568f);logoMaterial.color.setHex(0xff1736);updateBar();seedDebris();prepareLayer();knife.visible=true;updateKnife();$('level').textContent=`${copy.level} ${level}`;$('coins').textContent=coins;$('result').classList.remove('show');$('settings').classList.remove('show');$('hint').style.opacity=1;$('message').style.opacity=0;$('fill').style.width='0%';timer();}
const canvas=renderer.domElement;let activePointer=null;
function stopInput(){const pointer=activePointer;down=false;auto=false;activePointer=null;if(pointer!==null&&canvas.hasPointerCapture(pointer))canvas.releasePointerCapture(pointer);}
canvas.addEventListener('pointerdown',e=>{if(paused||completed||activePointer!==null)return;auto=false;down=true;if(returning)returnArmed=true;activePointer=e.pointerId;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!down||e.pointerId!==activePointer)return;const dy=e.clientY-lastY;lastY=e.clientY;if(Math.abs(dy)<.5)return;const direction=dy>0?1:-1;
 if(direction===1&&lastDragDirection===-1&&!returning&&cutY<CY+RY+.24){finishLayer();returnArmed=true;}
 lastDragDirection=direction;advance(targetY-dy/root.clientHeight*8);});
canvas.addEventListener('pointerup',stopInput);canvas.addEventListener('pointercancel',stopInput);canvas.addEventListener('lostpointercapture',stopInput);
window.addEventListener('keydown',e=>{if(e.code==='Space'&&!completed&&!paused&&!down){e.preventDefault();auto=true;}if(e.code==='KeyR'){stopInput();reset();}});window.addEventListener('keyup',e=>{if(e.code==='Space')auto=false;});window.addEventListener('blur',stopInput);
$('gear').onclick=()=>{paused=true;stopInput();$('settings').classList.add('show');};$('resume').onclick=()=>{paused=false;$('settings').classList.remove('show');};$('restart').onclick=()=>reset();$('again').onclick=()=>reset();$('next').onclick=()=>reset(layer===LAYERS);document.addEventListener('visibilitychange',()=>{if(document.hidden){paused=true;stopInput();$('settings').classList.add('show');}});
function resize(){const w=root.clientWidth,h=root.clientHeight,v=8.3;camera.left=-v*w/h/2;camera.right=v*w/h/2;camera.top=v/2;camera.bottom=-v/2;camera.updateProjectionMatrix();renderer.setSize(w,h);}window.addEventListener('resize',resize);resize();reset();$('loading').remove();let previous=performance.now();
function animate(now){requestAnimationFrame(animate);const realDt=Math.max(0,(now-previous)/1000),dt=Math.min(realDt,.045);previous=now;if(!paused){if(barDirty){barDirty=false;updateBar();}if(started&&!completed){elapsed+=realDt;timer();if($('timed').checked&&elapsed>=120)showResult(false);}if(!completed&&!cooldown){if(auto){advance(returning?targetY+dt*4.6:targetY-dt*4.6);}}animateReveal(dt);movePeel(dt);moveDebris(dt);if(cooldown>0){cooldown-=dt;if(cooldown<=0)finishLayer();}if(fallTime>0){fallTime-=dt;const t=1-Math.max(0,fallTime)/1.3,smooth=t*t*(3-2*t);rabbit.rotation.x=-Math.PI/2;rabbit.position.set(0,THREE.MathUtils.lerp(.26,.15,smooth),0);rabbit.scale.set(1,1,.8);}if(winDelay>0){winDelay-=dt;if(winDelay<=0)showResult(true);}if(msgTime>0){msgTime-=dt;if(msgTime<=0)$('message').style.opacity=0;}for(const p of confettiPieces){p.age+=dt;p.vel.y-=2.8*dt;p.pos.addScaledVector(p.vel,dt);dummy.position.copy(p.pos);dummy.rotation.set(p.age*3,p.age*2,p.age);dummy.scale.setScalar(Math.max(0,1-p.age/5));dummy.updateMatrix();conf.setMatrixAt(p.id,dummy.matrix);}if(confettiPieces.length)conf.instanceMatrix.needsUpdate=true;}renderer.render(scene,camera);}
requestAnimationFrame(animate);window.soapGame={getState:()=>({level,coins,layer,completed,paused,elapsed,cutY,cutCount,pieces:pieces.length,peeling:peeling.filter(p=>p.status==='peel').length}),renderer,scene,camera};
